server:
  port: 9001
  servlet:
    encoding:
      force: true
      charset: UTF-8
    session:
      timeout: 15
      tracking-modes: cookie
      cookie:
        http-only: true

spring:
  application:
    name: spring-sescurity-jwt-test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:person
    username: sa
    password: sa
    hikari:
      minimum-idle: 30
      maximum-pool-size: 100
      connection-timeout: 6000
      idle-timeout: 6000
      max-lifetime: 10000

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: true


jwt:
  secret : javainuse
  jwtExpirationInMilliSecond: 18000000